### PR TITLE
Remove status text options because people are complaining about taint

### PR DESCRIPTION
**Pull request by Ketho**
Users have been reporting taint, supposedly from the AIO Status Text options.
I'm sorry for that.

- https://www.curseforge.com/wow/addons/advancedinterfaceoptions#c505
- https://www.curseforge.com/wow/addons/advancedinterfaceoptions?page=2#c492
- https://www.curseforge.com/wow/addons/advancedinterfaceoptions?page=4#c432

### CODE REVIEW

**Comment by Stanzilla** [comment]
Are we sure this is actually our fault?

**Comment by Ketho** [comment]
@semlar agrees it's the most likely candidate, since it's the only thing touching Blizzard unit frames.
- https://www.townlong-yak.com/framexml/live/TextStatusBar.lua#14

Setting the `textLockable` field to false is a possible alternative but I haven't tested whether it will taint.
https://github.com/Ketho/AdvancedInterfaceOptions/commit/d5c2325c0212d1af6d279c71941d7889926c19d4

**Comment by Ketho** [comment]
Since I'm not sure, I can't reproduce it and Semlar just said that specific user didn't have latest version I'll close this pull request, sorry for that

**Comment by semlar** [comment]
I believe the status text settings are triggering the error by setting the .cvar keys on the frames which is causing some logic down the line to interfere with a secure action on the unit frames.

An alternative solution would be to hook the show/hide methods of the status text (or whatever blizzard function is responsible for deciding when to show them) and afterward call Show() or Hide() based on the user's settings.

**Comment by Stanzilla** [comment]
Can you ask Dan maybe? I am still on vacation until monday.

**Pull request closed without merging**
